install -c ./src/multichain/libbitcoin_multichain.a /usr/lib/
install -c ./src/multichain/tmp/libbitcoin_multichain.a /usr/lib/
install -c ./src/univalue/libbitcoin_univalue.a /usr/lib/
install -c ./src/libbitcoin_wallet.a /usr/lib/
install -c ./src/crypto/libbitcoin_crypto.a /usr/lib/
install -c ./src/.libs/libbitcoinconsensus.a /usr/lib/
install -c ./src/libbitcoin_server.a /usr/lib/
install -c ./src/libbitcoin_util.a /usr/lib/
install -c ./src/leveldb/libleveldb.a /usr/lib/
install -c ./src/leveldb/libmemenv.a /usr/lib/
install -c ./src/libbitcoin_common.a /usr/lib/
install -c ./src/libbitcoin_cli.a /usr/lib/
install -c ./src/secp256k1/.libs/libsecp256k1.a /usr/lib/
